---
name: hosts-demo
bundle_prefix:
  - ycappuccino.storage
  - demo
  - ycappuccino.hosts
layers:
  ycappuccino_storage_memory:
    active: true
config:
  http_server:
    active: true
    port: 8090
    ip: localhost
